# -*- coding: utf-8 -*-
"""Task 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H1oi4ojd85ujN60O17A22zEAQqCBFIFO
"""

#Load the data inside the provided CSV file into a Data Frame
import pandas as pd

df = pd.read_csv('Employees.csv')

print(df)

#Remove any duplicates in the table
df.drop_duplicates(inplace=True)
print(df)

#Remove any decimal places in the Age column
df['Age'] = df['Age'].astype(int)
print(df)

# Convert the USD salary to EGP
# the conversion rate today (19th of september) is 48.53 Egyptian Pound
df['Salary(USD)'] = df['Salary(USD)'] * 48.53
print(df)

df.rename(columns={'Salary(USD)': 'Salary(EGP)'}, inplace=True)
print(df)

'''Print in the console some stats like:
	- Average age
	- Median Salaries
	- Ratio between males and female employees
'''
Avg_Age = df['Age'].mean()
Median_Salaries = df['Salary(EGP)'].median()
gender_counts = df['Gender'].value_counts()
malesCount = gender_counts.get("M")
femalesCount = gender_counts.get("F")

print(f"Average Age is {Avg_Age}")
print(f"Median Salaries is {Median_Salaries}")
print(f"Males Count is {malesCount}")
print(f"Females Count is {femalesCount}")
print (f"Ratio of males to females employees {malesCount/femalesCount}")

#write the data in a new CSV file
df.to_csv('employees.csv', index=False)
